---
- description: InstallPackage
  buttons: submit,cancel
  label: InstallPackage
  blueprint_id: 
  dialog_tabs:
  - description: General
    display: edit
    label: General
    display_method: 
    display_method_options: 
    position: 0
    dialog_groups:
    - description: General
      display: edit
      label: General
      display_method: 
      display_method_options: 
      position: 0
      dialog_fields:
      - name: param_package_name
        description: Specify additional package to install
        data_type: 
        notes: 
        notes_display: 
        display: edit
        display_method: 
        display_method_options: {}
        required: false
        required_method: 
        required_method_options: {}
        default_value: ''
        values: 
        values_method: 
        values_method_options: {}
        options:
          :protected: false
        label: Package Name
        position: 0
        validator_type: 
        validator_rule: 
        reconfigurable: 
        dynamic: false
        show_refresh_button: 
        load_values_on_init: 
        read_only: false
        auto_refresh: 
        trigger_auto_refresh: 
        visible: true
        type: DialogFieldTextBox
        resource_action:
          action: 
          resource_type: DialogField
          ae_namespace: 
          ae_class: 
          ae_instance: 
          ae_message: 
          ae_attributes: {}
